version: '3.8'

services:
  server: 
    build: src/backend/.
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      APP_PORT: ${APP_PORT}
    restart: always
